# Day 24 Exercises

### 1: Checking numpy version

In [1]:
import numpy as np
    # How to check the version of the numpy package
print('numpy:', np.__version__)
    # Checking the available methods
print(dir(np))

numpy: 1.26.2
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_i

### 2: Creating numpy array

In [139]:
# Creating python List
python_list = [1,2,3,4,5]

    # Checking data types
print('Type:', type (python_list)) # <class 'list'>
    #
print(python_list) # [1, 2, 3, 4, 5]

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

    # Creating Numpy(Numerical Python) array from python list

numpy_array_from_list = np.array(python_list)
print(type (numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list) # array([1, 2, 3, 4, 5])

Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


### 3: Creating float numpy arrays

In [140]:
# Python list
python_list = [1,2,3,4,5]

numy_array_from_list2 = np.array(python_list, dtype=float)

print(numy_array_from_list2) # array([1., 2., 3., 4., 5.])


[1. 2. 3. 4. 5.]


### 4: Creating boolean numpy arrays, and multidimensional array using numpy

In [141]:

numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)

print(numpy_bool_array) # array([False,  True,  True, False, False])


two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)


[False  True  True False False]
<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5: Converting numpy array to list

In [142]:
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### 6: Creating numpy array from tuple

In [143]:
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) 
print('python_tuple: ', python_tuple) 

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) 
print('numpy_array_from_tuple: ', numpy_array_from_tuple) 

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


### 7: Shape of numpy array

In [144]:
nums = np.array([1, 2, 3, 4, 5])

print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)

three_by_four_array = np.array([[0, 1, 2, 3],
[4,5,6,7],
[8,9,10, 11]])

print(three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


### 8: Data type of numpy array

In [145]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


### 9: Size of a numpy array

In [146]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) 
print('The size:', two_dimensional_list.size) 

The size: 5
The size: 9


## Mathematical Operation using numpy
### 11: Addition

In [147]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_plus_original = numpy_array_from_list  + 10

print(ten_plus_original)


original array:  [1 2 3 4 5]
[11 12 13 14 15]


### 12: Subtraction

In [148]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_minus_original = numpy_array_from_list  - 10

print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


### 13: Multiplication

In [149]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list * 10

print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


### 14: Division

In [150]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list / 10

print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


### 15: Modulus

In [151]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list % 3

print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


### 16: Floor Division

In [152]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list // 3

print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 1 1 1]


### 17: Expoonential

In [153]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list ** 3

print(ten_times_original)

original array:  [1 2 3 4 5]
[  1   8  27  64 125]


### 18: Checking data types

In [154]:
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


### Converting data types
### 19: Int to Float

In [155]:
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr

array([1., 2., 3., 4.])

### 20: Float to Int

In [156]:
numpy_int_arr = np.array([1., 2., 3., 4.], dtype = 'int')
numpy_int_arr

array([1, 2, 3, 4])

### 21: Int to boolean

In [157]:
np.array([-3, -2, 0, 1,2,3], dtype='bool')

array([ True,  True, False,  True,  True,  True])

### 22: Int to str

In [158]:
#numpy_float_list = .astype('int').astype('str')

### Multi-dimensional Arrays
### 23: 2-Dimension Array

In [159]:
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])

print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int32


### 24: Getting items from a numpy array

In [160]:
#Example 1

two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]

print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

#Example 2

first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)


First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]
First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 25: Slicing Numpy array

In [161]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]

print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


### 26: Reversing rows and the whole array

In [162]:
two_dimension_array[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 27: Reversing the row and column positions

In [163]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 28: Representing missing values

In [164]:
print(two_dimension_array)

two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44

print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


### 29: Numpy zeroes

In [165]:
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_zeroes

numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 30: Numpy reshape

In [166]:
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

#Flattened
flattened = reshaped.flatten()
flattened

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

### 31: Horizontal stack

In [167]:
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


 ### 32: Vertical Stack

In [168]:
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]


### 33: Generating Random Numbers

In [169]:
# Generate a random float  number
random_float = np.random.random()
random_float

# Generate a random float  number
random_floats = np.random.random(5)
random_floats


array([0.30481438, 0.74640201, 0.33787519, 0.71312021, 0.97919705])

### 34: Generating a random integers between 0 and 10

In [170]:
random_int = np.random.randint(0, 11)
random_int


8

### 35: Generating a random integers between 2 and 11, and creating a one row array

In [171]:
random_int = np.random.randint(2,10, size=4)
random_int

array([3, 9, 7, 2])

### 36: Generating a random integers between 0 and 10

In [172]:
random_int = np.random.randint(2,10, size=(3,3))
random_int

array([[5, 6, 6],
       [9, 6, 8],
       [8, 2, 2]])

### 37: Generationg random numbers

In [173]:
normal_array = np.random.normal(79, 15, 80)
normal_array

array([ 56.97451317,  73.02748116,  87.10427882,  95.56121548,
        84.48954016,  56.92198022, 102.37508487,  79.2781389 ,
        93.44353523,  98.1457821 ,  75.73576306,  81.29199167,
        86.34749378,  91.3413432 ,  78.69467714,  94.46798312,
        64.14936097,  58.90734392,  76.35474418,  58.17028762,
        90.48034075,  77.72700104, 100.50359619,  72.70192502,
        69.34776363,  92.69267384, 106.27512712,  78.9882544 ,
        79.86944228,  96.65772514,  98.62573121,  90.2752605 ,
        93.67641741,  59.11709926,  81.27809559,  59.81031724,
        67.12974949,  62.11221008,  73.15630743,  95.98838426,
        81.69540492,  88.61932692,  85.07533184,  90.44330197,
        71.84668764,  90.78039935,  49.64392774, 102.00864005,
        88.63329716,  54.18331679,  63.20627582,  71.90972862,
        48.75260278,  98.25042855,  82.79552799,  77.24244966,
        57.23609374,  93.11089855, 103.31839432,  74.95604771,
        96.09444662,  69.86250535,  88.72268432,  76.08

### 38: Numpy and Statistics

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
plt.hist(normal_array, color="grey", bins=50)


ModuleNotFoundError: No module named 'matplotlib'

### 39: Matrix in numpy

In [ ]:
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))
four_by_four_matrix

### 40: numpy.arange()

In [ ]:
lst = range(0, 11, 2)
lst

range(0, 11, 2)

for l in lst:
    print(l)

In [ ]:
# Whole numbers
whole_numbers = np.arange(0, 20, 1)
whole_numbers

# Natural Numbers
natural_numbers = np.arange(1, 20, 1)
natural_numbers

# Odd Numbers
odd_numbers = np.arange(1, 20, 2)
odd_numbers

# Even Numbers
even_numbers = np.arange(2, 20, 2)
even_numbers

### 41: Creating sequence of numbers using linspace

In [ ]:
np.linspace(1.0, 5.0, num=10)

np.linspace(1.0, 5.0, num=5, endpoint=False)

np.logspace(2, 4.0, num=4)

### 42: Checking the size of an array

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x

### 43: indexing and Slicing NumPy Arrays in Python


In [ ]:
#Indexing
np_list = np.array([(1,2,3), (4,5,6)])
np_list

#Slicing
print('First row: ', np_list[0])
print('Second row: ', np_list[1])

print('First column: ', np_list[:,0])
print('Second column: ', np_list[:,1])
print('Third column: ', np_list[:,2])


### 44: NumPy Statistical Functions with Example

In [ ]:
## min, max, mean, median, sd
print('min: ', two_dimension_array.min())
print('max: ', two_dimension_array.max())
print('mean: ',two_dimension_array.mean())

# print('median: ', two_dimension_array.median())
print('sd: ', two_dimension_array.std())

print(two_dimension_array)
print('Column with minimum: ', np.amin(two_dimension_array,axis=0))
print('Column with maximum: ', np.amax(two_dimension_array,axis=0))
print('=== Row ==')
print('Row with minimum: ', np.amin(two_dimension_array,axis=1))
print('Row with maximum: ', np.amax(two_dimension_array,axis=1))


### 45: Creating repeating sequences

In [ ]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

### 46: Generating random numbers

In [ ]:
# One random number between [0,1)
one_random_num = np.random.random()
one_random_in = np.random
print(one_random_num)

# Random numbers between [0,1) of shape 2,3
r = np.random.random(size=[2,3])
print(r)

print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

## Random numbers between [0, 1] of shape 2, 2
rand = np.random.rand(2,2)
rand

rand_int = np.random.randint(0, 10, size=[5,3])
rand_int

### 47: Generating 

In [ ]:
from scipy import stats
np_normal_dis = np.random.normal(5, 0.5, 1000) # mean, standard deviation, number of samples
np_normal_dis
## min, max, mean, median, sd
print('min: ', np.min(np_normal_dis))
print('max: ', np.max(np_normal_dis))
print('mean: ', np.mean(np_normal_dis))
print('median: ', np.median(np_normal_dis))
print('mode: ', stats.mode(np_normal_dis))
print('sd: ', np.std(np_normal_dis))


In [ ]:
plt.hist(np_normal_dis, color="grey", bins=21)
plt.show()

![png](../test_files/test_121_0.png)

### Linear Algebra
### 48: Dot Product

In [ ]:
### Dot product: product of two arrays
f = np.array([1,2,3])
g = np.array([4,5,3])

### 1*4+2*5 + 3*6
np.dot(f, g)

### 49: NumPy Matrix Multiplication with np.matmul()

In [ ]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]

### 1*5+2*7 = 19
np.matmul(h, i)

### 50: Determinant 2*2 matrix

In [ ]:
### 5*8-7*6np.linalg.det(i)

#np.linalg.det(i)

Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1

Z

### 51: New list

In [ ]:
new_list = [ x + 2 for x in range(0, 11)]
new_list

In [ ]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1

Z

### 52: Linear equation for quantities which have linear relationship

In [ ]:
temp = np.array([1,2,3,4,5])
pressure = temp * 2 + 5
pressure

array([ 7,  9, 11, 13, 15])