# Day 24 Exercises

### 1: Checking numpy version

In [1]:
import numpy as np
    # How to check the version of the numpy package
print('numpy:', np.__version__)
    # Checking the available methods
print(dir(np))

numpy: 1.26.2
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_i

### 2: Creating numpy array

In [2]:
# Creating python List
python_list = [1,2,3,4,5]

    # Checking data types
print('Type:', type (python_list)) # <class 'list'>
    #
print(python_list) # [1, 2, 3, 4, 5]

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

    # Creating Numpy(Numerical Python) array from python list

numpy_array_from_list = np.array(python_list)
print(type (numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list) # array([1, 2, 3, 4, 5])

Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


### 3: Creating float numpy arrays

In [3]:
# Python list
python_list = [1,2,3,4,5]

numy_array_from_list2 = np.array(python_list, dtype=float)

print(numy_array_from_list2) # array([1., 2., 3., 4., 5.])


[1. 2. 3. 4. 5.]


### 4: Creating boolean numpy arrays, and multidimensional array using numpy

In [4]:

numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)

print(numpy_bool_array) # array([False,  True,  True, False, False])


two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)


[False  True  True False False]
<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5: Converting numpy array to list

In [5]:
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### 6: Creating numpy array from tuple

In [6]:
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) 
print('python_tuple: ', python_tuple) 

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) 
print('numpy_array_from_tuple: ', numpy_array_from_tuple) 

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


### 7: Shape of numpy array

In [7]:
nums = np.array([1, 2, 3, 4, 5])

print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)

three_by_four_array = np.array([[0, 1, 2, 3],
[4,5,6,7],
[8,9,10, 11]])

print(three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


### 8: Data type of numpy array

In [8]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


### 9: Size of a numpy array

In [9]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) 
print('The size:', two_dimensional_list.size) 

The size: 5
The size: 9


## Mathematical Operation using numpy
### 11: Addition

In [10]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_plus_original = numpy_array_from_list  + 10

print(ten_plus_original)


original array:  [1 2 3 4 5]
[11 12 13 14 15]


### 12: Subtraction

In [11]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_minus_original = numpy_array_from_list  - 10

print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


### 13: Multiplication

In [12]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list * 10

print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


### 14: Division

In [13]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list / 10

print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


### 15: Modulus

In [14]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list % 3

print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


### 16: Floor Division

In [15]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list // 3

print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 1 1 1]


### 17: Expoonential

In [16]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

print('original array: ', numpy_array_from_list)

ten_times_original = numpy_array_from_list ** 3

print(ten_times_original)

original array:  [1 2 3 4 5]
[  1   8  27  64 125]


### 18: Checking data types

In [17]:
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


### Converting data types
### 19: Int to Float

In [18]:
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr

array([1., 2., 3., 4.])

### 20: Float to Int

In [19]:
numpy_int_arr = np.array([1., 2., 3., 4.], dtype = 'int')
numpy_int_arr

array([1, 2, 3, 4])

### 21: Int to boolean

In [20]:
np.array([-3, -2, 0, 1,2,3], dtype='bool')

array([ True,  True, False,  True,  True,  True])

### 22: Int to str

In [21]:
#numpy_float_list = .astype('int').astype('str')

### Multi-dimensional Arrays
### 23: 2-Dimension Array

In [22]:
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])

print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int32


### 24: Getting items from a numpy array

In [23]:
#Example 1

two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]

print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

#Example 2

first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)


First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]
First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 25: Slicing Numpy array

In [24]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]

print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


### 26: Reversing rows and the whole array

In [25]:
two_dimension_array[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 27: Reversing the row and column positions

In [26]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 28: Representing missing values

In [27]:
print(two_dimension_array)

two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44

print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


### 29: Numpy zeroes

In [28]:
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_zeroes

numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 30: Numpy reshape

In [29]:
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

#Flattened
flattened = reshaped.flatten()
flattened

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

### 31: Horizontal stack

In [30]:
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


 ### 32: Vertical Stack

In [31]:
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]


### 33: Generating Random Numbers

In [32]:
# Generate a random float  number
random_float = np.random.random()
random_float

# Generate a random float  number
random_floats = np.random.random(5)
random_floats


array([0.78033155, 0.22131482, 0.86895211, 0.92395491, 0.69403115])

### 34: Generating a random integers between 0 and 10

In [33]:
random_int = np.random.randint(0, 11)
random_int


8

### 35: Generating a random integers between 2 and 11, and creating a one row array

In [34]:
random_int = np.random.randint(2,10, size=4)
random_int

array([2, 7, 3, 6])

### 36: Generating a random integers between 0 and 10

In [35]:
random_int = np.random.randint(2,10, size=(3,3))
random_int

array([[2, 7, 3],
       [6, 9, 9],
       [8, 6, 8]])

### 37: Generationg random numbers

In [36]:
normal_array = np.random.normal(79, 15, 80)
normal_array

array([ 74.83520832,  73.63321488,  80.86857178,  90.21523256,
        95.58483835, 103.93223514,  78.31052846,  70.28489443,
        88.77172671,  75.65562225,  92.35053484,  48.32369696,
        76.62560124, 114.48702488,  77.39998396,  35.61120303,
        73.57147363,  49.85325716,  52.30650049,  76.73773571,
        66.60105886,  99.10172062,  75.70437784,  82.34726526,
        72.8791721 ,  86.10452703,  72.69939273,  83.9635261 ,
       113.3145492 ,  59.5982638 ,  62.98952319,  89.87175691,
        82.87597913,  67.45637099,  79.36201491,  85.37833804,
        89.71143399,  50.38246667, 101.7889913 ,  66.85180595,
        80.70057797,  74.28397139,  70.36326053,  81.86851935,
        75.83682593,  82.82412606,  75.62098315,  78.00291914,
        95.30940654,  89.98074984,  81.08775251,  68.3272172 ,
        92.08950541,  96.03184717,  64.41743472,  76.02698516,
        79.11430376, 114.6423556 ,  55.71961097,  74.99600003,
        85.23298751,  72.50536937,  81.4653737 ,  82.87

### 38: Numpy and Statistics

In [37]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
plt.hist(normal_array, color="grey", bins=50)


ModuleNotFoundError: No module named 'matplotlib'

### 39: Matrix in numpy

In [38]:
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### 40: numpy.arange()

In [ ]:
lst = range(0, 11, 2)
lst

range(0, 11, 2)

for l in lst:
    print(l)

: 

In [ ]:
# Whole numbers
whole_numbers = np.arange(0, 20, 1)
whole_numbers

# Natural Numbers
natural_numbers = np.arange(1, 20, 1)
natural_numbers

# Odd Numbers
odd_numbers = np.arange(1, 20, 2)
odd_numbers

# Even Numbers
even_numbers = np.arange(2, 20, 2)
even_numbers

: 

### 41: Creating sequence of numbers using linspace

In [ ]:
np.linspace(1.0, 5.0, num=10)

np.linspace(1.0, 5.0, num=5, endpoint=False)

np.logspace(2, 4.0, num=4)

: 

### 42: Checking the size of an array

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x

: 

### 43: indexing and Slicing NumPy Arrays in Python


In [ ]:
#Indexing
np_list = np.array([(1,2,3), (4,5,6)])
np_list

#Slicing
print('First row: ', np_list[0])
print('Second row: ', np_list[1])

print('First column: ', np_list[:,0])
print('Second column: ', np_list[:,1])
print('Third column: ', np_list[:,2])


: 

### 44: NumPy Statistical Functions with Example

In [ ]:
## min, max, mean, median, sd
print('min: ', two_dimension_array.min())
print('max: ', two_dimension_array.max())
print('mean: ',two_dimension_array.mean())

# print('median: ', two_dimension_array.median())
print('sd: ', two_dimension_array.std())

print(two_dimension_array)
print('Column with minimum: ', np.amin(two_dimension_array,axis=0))
print('Column with maximum: ', np.amax(two_dimension_array,axis=0))
print('=== Row ==')
print('Row with minimum: ', np.amin(two_dimension_array,axis=1))
print('Row with maximum: ', np.amax(two_dimension_array,axis=1))


: 

### 45: Creating repeating sequences

In [ ]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

: 

### 46: Generating random numbers

In [ ]:
# One random number between [0,1)
one_random_num = np.random.random()
one_random_in = np.random
print(one_random_num)

# Random numbers between [0,1) of shape 2,3
r = np.random.random(size=[2,3])
print(r)

print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

## Random numbers between [0, 1] of shape 2, 2
rand = np.random.rand(2,2)
rand

rand_int = np.random.randint(0, 10, size=[5,3])
rand_int

: 

### 47: Generating 

In [ ]:
from scipy import stats
np_normal_dis = np.random.normal(5, 0.5, 1000) # mean, standard deviation, number of samples
np_normal_dis
## min, max, mean, median, sd
print('min: ', np.min(np_normal_dis))
print('max: ', np.max(np_normal_dis))
print('mean: ', np.mean(np_normal_dis))
print('median: ', np.median(np_normal_dis))
print('mode: ', stats.mode(np_normal_dis))
print('sd: ', np.std(np_normal_dis))


: 

In [ ]:
plt.hist(np_normal_dis, color="grey", bins=21)
plt.show()

![png](../test_files/test_121_0.png)

: 

### Linear Algebra
### 48: Dot Product

In [ ]:
### Dot product: product of two arrays
f = np.array([1,2,3])
g = np.array([4,5,3])

### 1*4+2*5 + 3*6
np.dot(f, g)

: 

### 49: NumPy Matrix Multiplication with np.matmul()

In [ ]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]

### 1*5+2*7 = 19
np.matmul(h, i)

: 

### 50: Determinant 2*2 matrix

In [ ]:
### 5*8-7*6np.linalg.det(i)

#np.linalg.det(i)

Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1

Z

: 

### 51: New list

In [ ]:
new_list = [ x + 2 for x in range(0, 11)]
new_list

: 

In [ ]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1

Z

: 

### 52: Linear equation for quantities which have linear relationship

In [ ]:
temp = np.array([1,2,3,4,5])
pressure = temp * 2 + 5
pressure

: 